/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChinaTaiwan2026RouteImport } from './routes/china-taiwan-2026'
import { Route as IndexRouteImport } from './routes/index'

const ChinaTaiwan2026Route = ChinaTaiwan2026RouteImport.update({
  id: '/china-taiwan-2026',
  path: '/china-taiwan-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/china-taiwan-2026': typeof ChinaTaiwan2026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/china-taiwan-2026': typeof ChinaTaiwan2026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/china-taiwan-2026': typeof ChinaTaiwan2026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/china-taiwan-2026'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/china-taiwan-2026'
  id: '__root__' | '/' | '/china-taiwan-2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChinaTaiwan2026Route: typeof ChinaTaiwan2026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/china-taiwan-2026': {
      id: '/china-taiwan-2026'
      path: '/china-taiwan-2026'
      fullPath: '/china-taiwan-2026'
      preLoaderRoute: typeof ChinaTaiwan2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChinaTaiwan2026Route: ChinaTaiwan2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
